/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { WorkflowTemplateProcess } from './WorkflowTemplateProcess';

/**
 * A workflow template artifact is part of a workflow template. It explains what kind of artifact is used or generated by the process template, along with possible restrictions that it may have.
 *
 * There are two different types of workflow template artifacts: data variables and parameter variables.
 */
export type WorkflowTemplateArtifact = {
    /**
     * Property that represents the dimensionality of the artifact: 0 is a single file, 1 for a collection, etc.
     *
     * Example:
     * @prefix opmw: <http://www.opmw.org/ontology/> .
     *
     * <http://www.opmw.org/export/resource/DataVariable/AQUAFLOW_NTM_DAILYDATA>
     * a opmw:DataVariable, opmw:WorkflowTemplateArtifact;
     * opmw:hasDimensionality "1"^^xsd:int.
     *
     */
    hasDimensionality?: Array<number> | null;
    /**
     * Property that binds a workflow template artifact to the workflow template process that generates it.
     *
     * Example:
     * @prefix opmw: <http://www.opmw.org/ontology/> .
     *
     * <http://www.opmw.org/export/resource/DataVariable/AQUAFLOW_EDM_REAERATIONPARAMS>
     * a opmw:DataVariable, opmw:WorkflowTemplateArtifact;
     * opmw:isGeneratedBy <http://www.opmw.org/export/resource/WorkflowTemplateProcess/AQUAFLOW_EDM_REAERATIONEDM>.
     *
     *
     */
    isGeneratedBy?: Array<WorkflowTemplateProcess> | null;
    /**
     * small description
     */
    description?: Array<string> | null;
    /**
     * identifier
     */
    id?: string;
    /**
     * short description of the resource
     */
    label?: Array<string> | null;
    /**
     * type of the resource
     */
    type?: Array<string> | null;
};

