/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $WorkflowTemplateArtifact = {
    description: `A workflow template artifact is part of a workflow template. It explains what kind of artifact is used or generated by the process template, along with possible restrictions that it may have.

    There are two different types of workflow template artifacts: data variables and parameter variables.`,
    properties: {
        hasDimensionality: {
            type: 'array',
            contains: {
                type: 'number',
                format: 'int32',
            },
            isNullable: true,
        },
        isGeneratedBy: {
            type: 'array',
            contains: {
                type: 'WorkflowTemplateProcess',
            },
            isNullable: true,
        },
        description: {
            type: 'array',
            contains: {
                type: 'string',
            },
            isNullable: true,
        },
        id: {
            type: 'string',
            description: `identifier`,
        },
        label: {
            type: 'array',
            contains: {
                type: 'string',
            },
            isNullable: true,
        },
        type: {
            type: 'array',
            contains: {
                type: 'string',
            },
            isNullable: true,
        },
    },
} as const;
